#python mysql connectivity using tkinter
#Program:
importtkinterastk
importmysql.connector
fromtkinterimport*
defsubmitact():
user=Username.get()
passw=password.get()
print(f"Thenameenteredbyyouis{user}{passw}")
logintodb(user,passw)
deflogintodb(user,passw):
#Ifpasswordisenteredbythe
#user
ifpassw:
db=mysql.connector.connect(host="localhost",
user=user,
password=passw,
db="College")
cursor=db.cursor()
#Ifnopasswordisenteredbythe
#user
else:
db=mysql.connector.connect(host="localhost",
user=user,
db="College")
cursor=db.cursor()
#ATableinthedatabase
savequery="select*fromSTUDENT"
try:
cursor.execute(savequery)
myresult=cursor.fetchall()
#Printingtheresultofthe
#query
forxinmyresult:
print(x)
print("QueryExecutedsuccessfully")
except:
db.rollback()
print("Erroroccurred")
root=tk.Tk()
root.geometry("300x300")
root.title("DBMSLoginPage")
#Definingthefirstrow
lblfrstrow=tk.Label(root,text="Username-",)
lblfrstrow.place(x=50,y=20)
Username=tk.Entry(root,width=35)
Username.place(x=150,y=20,width=100)
lblsecrow=tk.Label(root,text="Password-")
lblsecrow.place(x=50,y=50)
password=tk.Entry(root,width=35)
password.place(x=150,y=50,width=100)
submitbtn=tk.Button(root,text="Login",
bg='blue',command=submitact)
submitbtn.place(x=150,y=135,width=55)
root.mainloop()

